[package]
name = "rdza_game_test"
version = "0.1.0"
authors = ["Paweł Nowiński"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = {version="0.32.2", features=[]}

[target.'cfg(windows)'.dependencies]
sdl2 = {version="0.32.2", features=["static-link", "bundled"]}